---
openapi: 3.0.1
info:
  title: TicketAppProject API
  description: Main API Information
  version: '1.0'
servers:
- url: http://localhost:8082
  description: Generated server url
paths:
  "/payments":
    post:
      tags:
      - payment-controller
      operationId: createOrUpdatePayment
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/PaymentDto"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/PaymentDto"
  "/payments/{travelId}":
    get:
      tags:
      - payment-controller
      operationId: getPaymentsOfTravel
      parameters:
      - name: travelId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/PaymentDto"
  "/payments/{email}/{travelId}/{seatNumber}":
    get:
      tags:
      - payment-controller
      operationId: getPaymentOfTicket
      parameters:
      - name: email
        in: path
        required: true
        schema:
          type: string
      - name: travelId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: seatNumber
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/PaymentDto"
components:
  schemas:
    PaymentDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userEmail:
          type: string
        paymentType:
          type: string
          enum:
          - CREDIT_CARD
          - EFT
        iban:
          type: string
        cardNumber:
          type: string
        travelId:
          type: integer
          format: int64
        seatNumber:
          type: integer
          format: int32
        securityCode:
          type: string
        amount:
          type: number
        paymentTime:
          type: string
          format: date-time
        isCanceled:
          type: boolean
